#+title:Breves notas sobre as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes no Regulamento dos Serviços Digitais
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil date:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+ODT_STYLES_FILE: "~/Dropbox/Bibliografia/ODT/modelo.odt"

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl chicago-rmartinez.csl

*Summary:*  The Digital Services Regulation amends the E-Commerce Directive, which since 2000 has established the general regulatory framework for the provision of information society services in the internal market. Since then, the Internet has evolved and new and innovative services and business models have emerged, such as online social networks and online marketplaces. This study focuses on online marketplaces, with brief notes on the additional provisions applicable to providers of online platforms that allow consumers to conclude distance contracts with traders.

*Sumário:* O Regulamento dos Serviços Digitais altera a Diretiva sobre o comércio eletrónico, na qual se consagrou, desde 2000, o enquadramento normativo geral para a prestação de serviços da sociedade da informação no mercado interno. Desde então, a /Internet/ evoluiu e apareceram novos e inovadores serviços e modelos de negócios, como as redes sociais e os /marketplaces/. É  sobre os /marketplaces/ ou mercados em linha que incide o presente estudo, no qual se efetuam breves notas sobre as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes.

* I. Introdução

O Regulamento dos Serviços Digitais altera[fn:1a] a Diretiva sobre o comércio eletrónico[fn:4a], na qual se consagrou, desde 2000, o enquadramento normativo geral para a prestação de serviços da sociedade da informação no mercado interno, com ênfase na sua livre circulação[cite:Cf., neste sentido, @demiguelasensio2023 p. 30] e na ideia de que a atividade dos prestadores de serviços intermediários era predominantemente técnica e passiva no que respeita a conteúdos[cite:Cf., neste sentido, @leitao2023 pp. 9-10]. Esta ideia mostra-se, no entanto, desfasada face à evolução da /Internet/, nomeadamente em virtude do aparecimento de novos e inovadores serviços e modelos de negócios, como as redes sociais e os /marketplaces/. O presente estudo incide sobre os /marketplaces/ ou mercados em linha, efetuando-se breves notas sobre as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes, consagradas no Regulamento dos Serviços Digitais. De seguida, analisa-se a delimitação subjetiva (II.), a obrigação de rastreabilidade dos comerciantes (III.), a obrigação de conformidade desde a conceção (IV.) e as obrigações de informação e divulgação em caso de oferta, na plataforma em linha, de produtos ou serviços ilegais (V.). Termina-se apresentando breves considerações finais (VI.).

* II. Delimitação subjetiva

As obrigações de rastreabilidade dos comerciantes, conformidade desde a conceção e de informação e divulgação em caso de oferta, na plataforma em linha, de produtos ou serviços ilegais são aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes. O conceito de "plataformas em linha que permitem aos consumidores celebrar contratos com comerciantes" parece muito próximo do conceito de "mercado em linha"[fn:19], mas não inclui as plataformas que apenas permitem a celebração de contratos entre consumidores[cite:Cf. @wilman2024, p. 224, n.º 8; @hofmann2023, art. 30.º, n.º 8]. Assim, e por exemplo, o fornecedor de plataforma em linha que /ou/ não permita a celebração de contratos à distância /ou/ só permita a celebração de contratos à distância entre consumidores não está obrigado a cumprir as disposições adicionais consagradas na secção IV do capítulo III.

O artigo 29.º consagra uma isenção subjetiva a favor das micro e pequenas empresas, na aceção da Recomendação 2003/361/CE[fn:7], e é o resultado da procura de um equilíbrio entre dois interesses, ambos consagrados no TFUE[fn:51]: a proteção dos consumidores[fn:16] e o apoio e desenvolvimento das micro, pequenas e médias empresas da União Europeia[fn:50]. Esta isenção subjetiva visa evitar encargos desproporcionados[fn:4], pois as empresas de menor dimensão poderão não conseguir suportar os custos de /compliance/ com todas as obrigações definidas no Regulamento dos Serviços Digitais e acabariam prejudicadas por um instrumento que visa também proporcionar-lhes condições de concorrência equitativas[fn:5].

De acordo com o TJUE, o conceito de micro, pequenas e médias empresas (PME) da Recomendação 2003/361/CE deve ser objeto de interpretação estrita, pois as vantagens concedidas às PME constituem, muitas vezes, exceções às regras gerais[fn:14] [cite:Cf. @hofmann2023, art. 29.º, n.º 7, defendem que a interpretação não deve ser estrita, mas sim tendo em conta a sua função específica].

Como a exclusão abrange as micro e as pequenas empresas, bastará cumprir os critérios definidos na recomendação para estas últimas para beneficiar da exclusão[cite:Cf., no mesmo sentido, @hofmann2023, art. 29.º, n.º 10]. Sendo a exclusão um benefício concedido aos fornecedores de plataformas em linha que permitam a celebração de contratos à distância com consumidores que sejam, na aceção da Recomendação 2003/361/CE, uma micro ou uma pequena empresa, nada impede que estes voluntariamente cumpram uma ou mais das obrigações previstas nesta secção[cite:Cf., considerando n.º 57 e @muller-terpitz2023, art. 29.º, n.º 6].

Em caso de perda do estatuto que confere a isenção, o fornecedor beneficia de um período de transição de 12 meses contados a partir da data em que perdeu o estatuto de micro ou pequena empresa[fn:76]. Este período de transição compreende-se como forma de mitigar os encargos inerentes ao cumprimento das obrigações desta secção.

Os fornecedores de plataformas em linha que permitam a celebração de contratos à distância que tenham sido designadas como plataformas em linha de muito grande dimensão[fn:77] não beneficiam da exclusão nem do período de transição em caso de perda do estatuto de micro ou pequena empresa [cite:Cf., respetivamente, artigo 29.º, n.º 2 e n.º 1, 2.º paragrafo, e @leitao2023, p. 76]. Embora improvável, é possível que uma micro ou pequena empresa seja a fornecedora de uma plataforma de muito grande dimensão, pois os critérios de determinação das micro e pequenas empresas são distintos dos da determinação das plataformas em linha de muito grande dimensão[cite:Cf. @wilman2024, art. 29.º, n.º 5]. Considerando o maior alcance e impacto das plataformas em linha de muito grande dimensão (que têm um número médio mensal de destinatários activos do serviço na União Europeia igual ou superior a 45 milhões), o legislador considerou que o valor da proteção dos consumidores deve prevalecer sobre o apoio às micro e pequenas empresas. Assim, mesmo que o fornecedor da plataforma em linha de muito grande dimensão seja uma micro ou pequena empresa, na aceção da Recomendação 2003/361/CE, ele encontra-se obrigado ao cumprimento das disposições da presente secção.

Caso o fornecedor seja uma micro ou pequena empresa, na aceção da Recomendação 2003/361/CE, e a sua plataforma em linha que permite a celebração de contratos à distância seja designada pela Comissão Europeia como uma plataforma em linha de muito grande dimensão pode questionar-se a partir de que data devem ser cumpridas as disposições previstas nos artigos 30.º a 32.º. Resulta do artigo 33.º, n.º 6, 2.º parágrafo, que as obrigações adicionais dos fornecedores de plataformas em linha de muito grande dimensão e de motores de pesquisa em linha de muito grande dimensão no que se refere à gestão de riscos sistémicos (secção 5 do capítulo III) são aplicáveis no prazo de quatro meses após a notificação da designação ao fornecedor. Não há preceito equivalente para as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes (secção 4 do capítulo III). Apesar disso, considerando a ponderação de interesses acima referida, o teor das obrigações previstas nos artigos 30.º a 32.º, a caracterização do fornecedor como micro ou pequena empresa na aceção da Recomendação 2003/361/CE e a classificação como plataforma em linha de muito grande dimensão depender de uma decisão da Comissão Europeia, parece adequado aplicar analogicamente o prazo de quatro meses para o fornecedor assegurar o cumprimento das obrigações previstas na presente secção.

* III. Obrigação de rastreabilidade dos comerciantes

** 1. Considerações gerais

A obrigação de rastreabilidade visa "contribuir para um ambiente em linha seguro, fiável e transparente para os consumidores, bem como para outras partes interessadas, como comerciantes concorrentes e titulares de direitos de propriedade intelectual"[fn:17] e assenta no princípio /Know Your Business Customer/[cite:Cf., neste sentido, @wilman2024, art. 30.º, n.º 2; @hofmann2023, art. 30.º, n.º 1;@muller-terpitz2023, art. 30.º, n.º 2;@leitao2023, p. 76;@tommasi2023b, p. 25]. Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes devem recolher e disponibilizar informação sobre os comerciantes[fn:1], antes de os autorizarem a dirigirem, através da plataforma em linha, a sua atividade aos consumidores localizados na União Europeia. A informação recolhida permitirá rastrear os comerciantes, promovendo a transparência e melhorando a proteção dos consumidores e de outras partes interessadas[cite:Cf. @mast2024, art. 30.º, n.º 3;e, no contexto da Proposta, @lodder2022, pp. 552-553]. Espera-se também que dissuada os comerciantes de venderem produtos ou serviços em violação das regras aplicáveis[fn:18].

A obrigação de rastreabilidade dos comerciantes está limitada em função do âmbito de aplicação espacial do Regulamento dos Serviços Digitais[cite:Cf. art. 2.º. Sobre o âmbito de aplicação do Regulamento dos Serviços Digitais, cf. @almeida (no prelo);@bessa2024;@hofmann2023 art. 2.º;@muller-terpitz2023 art. 2.º;@wilman2024 art. 2.º;@mast2024 art. 2.º] Deste modo, se o comerciante não prestar as informações mencionadas no n.º 1 ou se não as corrigir ou atualizar dentro do prazo fixado no n.º 3, o fornecedor da plataforma tem o dever de, respetivamente, /(i)/ não autorizar ou /(ii)/ suspender a utilização da plataforma pelo comerciante para promover mensagens ou oferecer produtos ou serviços /apenas aos consumidores localizados na União Europeia/. Tal significa que nestes casos o fornecedor cumpre o artigo 30.º se recusar a autorização ou suspender a utilização da sua plataforma pelo comerciante apenas aos consumidores localizados na União Europeia, por exemplo, através do mecanismo de bloqueio geogrático, permitindo que o comerciante continue a usar a plataforma para dirigir a sua atividade aos consumidores localizados fora da União Europeia[cite:Cf., no mesmo sentido, @hofmann2023, art. 30.º, n.º 12].

A rastreabilidade dos comerciantes tem por objeto a utilização das plataformas em linha para "promover mensagens e oferecer produtos ou serviços". A promoção de mensagens pelo comerciante parece reconduzível ao conceito de "anúncio publicitário"[fn:78]. As noções de "produtos" e "serviços" parecem ser, respetivamente, as definidas no artigo 2.º, n.º 5, da Diretiva relativa a certos aspetos dos contratos de compra e venda de bens[fn:20] e no artigo 4.º, n.º 1, da Diretiva serviços[fn:21]. Não está abrangida a conclusão do contrato[cite:Cf., neste sentido, @hofmann2023, art. 30.º, n.º 12;@muller-terpitz2023, art. 30.º, n.º 6].

** 2. Recolha de informação

Segundo o artigo 30.º, n.º 1, os fornecedores das plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes têm a obrigação de não permitir a utilização da sua plataforma pelo comerciante para promover mensagens ou oferecer produtos e serviços aos consumidores localizados na União Europeia /antes/ de recolhida a informação elencada neste número. O fornecedor pode permitir que o comerciante: /(i)/ utilize a plataforma em linha em momento anterior ao da prestação da informação para realizar atos diferentes da promoção de mensagens ou oferta de produtos ou serviços, como, por exemplo, a organização da sua "loja virtual" na plataforma em linha[cite:Cf. @hofmann2023, art. 30.º, n.º 11]; /(ii)/ dirija a sua atividade para os consumidores localizados fora da União Europeia.

No que respeita à informação a obter, o nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante[fn:52] visam facilitar a identificação e o contacto com o comerciante e promover um ambiente em linha mais seguro, em primeira linha para os consumidores. Neste contexto, o comerciante (seja ele pessoa singular ou coletiva) deve indicar o seu nome completo. O endereço postal deve corresponder à morada onde o comerciante pode ser judicialmente demandado (podendo, consoante os casos, ser uma das que resulta da aplicação dos artigos 4.º, 7.º, n.º 5, ou 17.º, n.º 2, conjugados com o artigo 63.º, todos do Regulamento Bruxelas I /bis/[fn:23]). A indicação de um número telefone é obrigatória, divergindo do que decidiu o TJUE no contexto da Diretiva relativa aos direitos dos consumidores[fn:22] [fn:24]. Por fim, o endereço de correio eletrónico indicado deve permitir o efetivo contacto com o comerciante e não pode ser um endereço configurado com respostas automáticas que remetam para outros meios de contacto[cite:Cf. @hofmann2023, art. 30.º, n.º 19].

O fornecedor deve receber cópia do documento de identificação do comerciante[fn:53]. No caso de comerciantes com cartão do cidadão português, a cópia pode ser substituída pelo documento pdf gerado pela aplicação móvel gov.pt, ao abrigo do Regulamento eIDAS[fn:25].

O fornecedor deve também receber informações sobre a conta de pagamento do comerciante[fn:54]. A noção de "conta de pagamento" não está definida no Regulamento dos Serviços Digitais, mas corresponde à definição constante do artigo 2.º, n.º 22, do Regulamento relativo às taxas de intercâmbio aplicáveis a operações de pagamento baseadas em cartões[fn:27].

Caso o comerciante esteja inscrito no registo comercial ou em outro registo público equivalente, o fornecer deve receber a informação de que o comerciante se encontra inscrito e o seu número de registo[fn:55].

Por fim, o fornecedor deve receber uma autocertificação do comerciante em que este se compromete a oferecer apenas produtos ou serviços que respeitem as regras aplicáveis do direito da União[fn:56]. Esta autocertificação tem um carácter geral[cite:Cf. @wilman2024, art. 30.º, n.º 7]. É dúvidoso que esta autocertificação seja eficaz na promoção de um ambiente em linha mais seguro ou seja um dissuasor para os comerciantes que pretendam dirigir a sua atividade para o mercado da União Europeia sem cumprir as regras que aí são aplicáveis[cite:Suscitando dúvidas similares, cf. @hofmann2023, art. 30.º, n.º 23;@muller-terpitz2023, art. 30.º, n.º 14] [fn:3].

** 3. Avaliação prévia da informação obtida

Recebidas as informações elencadas no n.º 1, o fornecedor deve envidar todos os esforços para avaliar se as informações recebidas são fiáveis e completas antes de permitir a utilização da sua plataforma pelo comerciante para propor mensagens e oferecer produtos ou serviços aos consumidores localizados na União Europeia. Esta obrigação de avaliação prévia da informação obtida é uma novidade.

O fornecedor deve avaliar se as informações são fiáveis e completas. Verificar se as informações estão ou não completas não parece suscitar dificuldades de maior[cite:Cf. @wilman2024, art. 30.º, n.º 15]. Para avaliar a fiabilidade das informações sugere-se a utilização de "bases de dados oficiais em linha e interfaces em linha de livre acesso, como registos comerciais nacionais e o Sistema de Intercâmbio de Informações sobre o IVA, ou solicitar aos comerciantes em causa que forneçam documentos comprovativos fiáveis, como cópias de documentos de identidade, extratos certificados de contas de pagamento, certificados de empresa e certidões de registo comercial", admitindo-se ainda o recurso "a outras fontes, disponíveis para utilização à distância, que proporcionem um grau de fiabilidade semelhante para efeitos de cumprimento desta obrigação"[fn:28]. A verificação da fiabilidade da autocertificação parece problemática, uma vez que incide sobre comportamentos futuros[cite:Cf. @wilman2024, art. 30.º, n.º 16].

O fornecedor não é obrigado a verificar a exatidão das informações recebidas. O responsável pela exatidão das informações é o comerciante[fn:57]. Se, no entanto, o fornecedor tiver conhecimento de que as informações são inexatas, não deve autorizar a utilização da plataforma antes da correção das mesmas pelo comerciante[cite:Cf., neste sentido, @hofmann2023, art. 30.º, n.º 29].

Estabelece-se que o fornecedor deve "envidar todos os esforços" para avaliar se as informações são fiáveis e completas. Esta expressão deve ser interpretada com cautela e compaginada com o esclarecimento no considerando n.º 73 de que "os fornecedores de plataformas em linha em causa não deverão ser obrigados a realizar exercícios de apuramento de factos em linha excessivos ou dispendiosos, nem a efetuar verificações desproporcionadas no local". Considera-se que o critério de diligência a adotar é o de "melhores esforços"[cite:Cf. @wilman2024, art. 30.º, n.º 13;@hofmann2023, art. 30.º, n.º 25;@muller-terpitz2023, art. 30.º, n.º 18], correspondente à versão em língua inglesa /"best efforts"/ e também ao artigo 17.º, n.º 4 da Directiva relativa aos direitos de autor e direitos conexos no mercado único digital[fn:58]. O conceito de "melhores esforços" não se encontra definido no Regulamento dos Serviços Digitais e deve ser objeto de interpretação autónoma, a qual deve atender à finalidade e objetivos do artigo 30.º e do Regulamento dos Serviços Digitais. Ainda assim, pensa-se que é possível traçar paralelos com a utilização do conceito no artigo 17.º, n.º 4 da Directiva relativa aos direitos de autor e direitos conexos no mercado único digital e tomar em consideração as orientações da Comissão Europeia sobre este conceito nessa sede[fn:31]. Trata-se de uma obrigação de meios[cite:Cf., no mesmo sentido, @rocha2024 pp. 31-32;@mast2024, art. 30.º, n.º 24], o que se compreende em face do artigo 8.º e da vontade de não impor encargos desproporcionados[fn:30]. Deve ser feita uma análise casuística, atendendo às circunstâncias do caso concreto e à complexidade da avaliação, sempre tendo em atenção o princípio da proporcionalidade[cite:Cf., no contexto do artigo 31.º, @rocha2024 pp. 39-40]. Pode questionar-se se o fornecedor empregou os seus "melhores esforços", se efetuou a sua avaliação com base num (e apenas um) dos elementos elencados no artigo 30.º, n.º 2[cite:Cf. @hofmann2023, art. 30.º, n.º 26]. Atendendo à natureza casuística do conceito, a resposta afirmativa ou negativa a esta questão dependerá das circunstâncias do caso concreto.

** 4. Informação inexata, incompleta ou desatualizada

Pode suceder que o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes obtenha indicações suficientes ou tenha motivos para supor que a informação que obteve de um comerciante é inexata, incompleta ou está desatualizada. Nesse caso, o fornecedor deve solicitar ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional[fn:59].

São informações inexatas aquelas que não correspondem à realidade (/v.g./, o comerciante indica um número de telefone que não lhe pertence). São informações incompletas aquelas em que não consta a totalidade da informação necessária (/v.g./, o comerciante indica a rua, cidade e país da sua sede, mas não indica o n.º da porta). Informações desatualizadas são informações que eram exatas e completas quando foram prestadas, mas que se tornaram inexatas com o decurso de tempo (/v.g./, o comerciante indicou a morada da sede, mas, posteriormente, transferiu a sede para outro local). Na verdade, crê-se que as informações desatualizadas serão sempre informações inexatas e, por isso, duvida-se que as mesmas tenham autonomia face a estas últimas[cite:Cf. @muller-terpitz2023, art. 30.º, n.º 31].

O dever do fornecedor de solicitar a correção ao comerciante surge quando obtiver indicações suficientes ou motivos para supor que as informações prestadas são inexatas, incompletas ou desatualizadas. O conceito de indicações suficientes não é definido no Regulamento dos Serviços Digitais. Pensa-se que será uma indicação suficiente, por exemplo, uma comunicação de um consumidor a informar que o endereço de correio eletrónico disponibilizado pelo comerciante não permite o contacto. Quanto aos motivos para supor, considera-se que eles permitem ao fornecedor efetuar uma verificação oficiosa da correção, completude e atualidade das informações prestadas pelo comerciante[cite:Cf. @hofmann2023, art. 30.º, n.ºs 36 e 37;@muller-terpitz2023, art. 30.º, n.º 28].

O fornecedor deve solicitar ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional. Visa-se uma correção sem atrasos indevidos. Não parece possível fixar o prazo de forma rígida, uma vez que o mesmo deverá atender às circunstâncias do caso concreto, nomeadamente à dificuldade de efetuar a correção[cite:Cf. @hofmann2023, art. 30.º, n.º 42].

Efetuada a solicitação de correção das informações, o comerciante pode /(i)/ corrigir as informações dentro do prazo fixado, /(ii)/ corrigir as informações fora do prazo ou /(iii)/ pode não corrigir as informações. No primeiro caso, o fornecedor deve manter o serviço e pode examinar as informações corrigidas para apurar se há novas informações inexatas, incompletas ou desatualizadas. Nos segundo e terceiro casos, o fornecedor deve suspender rapidamente o serviço que presta ao comerciante, mas apenas quanto aos consumidores localizados na União Europeia (o que pode ser feito recorrendo ao mecanismo de bloqueio geográfico). A diferença entre o segundo e terceiro casos, encontra-se na possibilidade de o comerciante vir a efetuar, tardiamente, a correção das informações. Nesse caso é sustentado que o fornecedor deve examinar a informação antes de levantar a suspensão[cite:Cf. @hofmann2023, art. 30.º, n.º 44].

** 5. Direito de apresentar uma reclamação

Nos casos em que um fornecedor de uma plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes se recuse a autorizar um comerciante a utilizar o seu serviço ao abrigo do n.º 1 ou suspenda a utilização do seu serviço ao abrigo do n.º 3, o comerciante tem o direito de apresentar uma reclamação nos termos dos artigos 20.º e 21.º, em acréscimo ao direito previsto no artigo 4.º, n.º 3 do Regulamento P2B[fn:32].

** 6. Conservação da informação
O fornecedor de plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes está obrigado a armazenar as informações que obtenha ao abrigo dos n.ºs 1 e 2 de forma segura até que decorram seis meses contados do termo da relação contratual com o comerciante. Durante esse período os dados devem ser conservados de forma segura, isto é utilizando meios tecnológicos adequados para garantir a segurança dos dados recebidos, atendendo também à natureza destes[cite:Cf. @muller-terpitz2023, art. 30.º, n.º 38]. Findo o prazo de conservação, o fornecedor deve apagar os dados, salvo se estiver sujeito a outras eventuais "obrigações de conservar determinados conteúdos durante períodos de tempo mais longos previstas no direito da União ou direito nacional que seja conforme com direito da União"[fn:35].

Esta obrigação de tratamento de dados visa "permitir que sejam apresentadas reclamações contra o comerciante ou que sejam cumpridas as decisões relacionadas com o comerciante" e é considerada pelo legislador europeu "necessária e proporcionada para que as informações possam ser acedidas, nos termos da legislação aplicável, nomeadamente em matéria de proteção de dados pessoais, por autoridades públicas e entidades privadas com um interesse legítimo, incluindo através das decisões de prestação de informações referidas no presente regulamento"[fn:33].

** 7. Divulgação da informação
O fornecedor só pode divulgar as informações obtidas ao abrigo dos n.ºs 1 e 2 a terceiros quando tal lhe seja exigido nos termos do Direito aplicável. O artigo 30.º, n.º 6, enuncia, sem limitar, que o fornecedor deve divulgar as informações quando tal lhe seja exigido no contexto de uma decisão do artigo 10.º ou de quaisquer decisões emitidas pelas autoridades competentes dos Estados-Membros ou pela Comissão para o desempenho das suas funções nos termos do presente regulamento. Este preceito releva, primordialmente, para conseguir o acesso às informações sobre os dados relativos ao documento de identificação e os dados da conta de pagamento do comerciante[fn:60].

As informações relativas /(i)/ ao nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante, /(ii)/ ao registo comercial ou outro registo público equivalente, se o comerciante estiver inscrito e /(iii)/ à autocertificação devem ser disponibilizadas aos destinatários de forma clara, facilmente acessível e compreensível e pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas. A informação é divulgada de forma clara se for facilmente identificável, procurando evitar-se ambiguidades e dúvidas interpretativas[cite:Cf. @muller-terpitz2023, art. 30.º, n.º 43]. A informação é divulgada de forma facilmente acessível se o destinatário do serviço consegue aceder à informação sem necessitar de pesquisar muito por ela[cite:Cf. @hofmann2023, art. 30.º, n.º 51], não devendo a interface em linha constituir um entrave ao acesso à informação[cite:Cf., no contexto do artigo 14.º, @knapp2024, p. 113]. Por fim, a informação é divulgada de forma compreensível se for fácil de apreender para o destinatário do serviço. Atendendo a que a norma visa, em primeira linha, a proteção dos consumidores, o critério pode ser a facilidade de compreensão para o consumidor médio[cite:Cf. @muller-terpitz2023, art. 30.º, n.º 44].

O fornecedor deve disponibilizar as informações pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas[fn:61]. Exige-se que a informação seja disponibilizada no mesmo local onde são apresentadas as informações sobre produto ou servço e permite-se que o fornecedor disponibilize a mesma informação em qualquer outro local da sua plataforma[fn:9].

* IV. Obrigação de conformidade desde a conceção
** 1. Considerações gerais

O artigo 31.º visa reforçar a proteção dos consumidores, através da conceção técnica das plataformas em linha (/law by design/)[cite:Cf. @rocha2024 pp. 35-36;@hofmann2023, art. 31.º, n.º 3;@muller-terpitz2023, art. 31.º, n.º 2;@mast2024, art. 31, n.º 3]. O Direito Europeu tem hoje um conjunto vasto de obrigações que impendem sobre o comerciante e que visam proteger o consumidor[fn:39]. Com este preceito, impõe-se aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes três obrigações distintas: /(i)/ a obrigação de conceber e organizar a sua interface de forma a que os comerciantes cumpram as suas obrigações em matéria de informação pré-contratual, conformidade e informação sobre a segurança dos produtos nos termos do direito da União aplicável[fn:62]; /(ii)/ a obrigação de verificar se os comerciantes prestaram as informações a que se refere o artigo 31.º, n.ºs 1 e 2, antes de permitirem que estes ofereçam os seus produtos ou serviços na plataforma em linha[fn:63]; e /(iii)/ a obrigação de verificar, posteriormente e por amostragem, se os produtos ou serviços oferecidos na sua plataforma em linha foram identificados como ilegais[fn:64].

Estas obrigações estão limitadas em função do âmbito de aplicação espacial do Regulamento dos Serviços Digitais[fn:65]. Apesar de apenas o artigo 31.º, n.º 2, al. /a)/, mencionar expressamente a localização dos consumidores na União Europeia, entende-se que todas as obrigações estabelecidas pelo artigo 31.º só são aplicáveis quando os comerciantes querem dirigir ou dirigem a sua atividade aos consumidores localizados na União Europeia. Assim, e por exemplo, o artigo 31.º não é aplicável e o fornecedor da plataforma em linha pode autorizar a utilização da sua plataforma em linha por um comerciante nos casos em que - através de um mecanismo tecnológico, como o bloqueio geográfico - este só possa dirigir a sua atividade para consumidores localizados /fora/ da União Europeia.

** 2. Obrigação de conceção e organização da interface em linha
O interface em linha[fn:66] deve ser concebido e organizado de modo a promover o cumprimento pelos comerciantes das suas obrigações em três matérias distintas, a saber: /(i)/ informações pré-contratuais; /(ii)/ conformidade; e /(iii)/ informação sobre a segurança dos produtos.

Em matéria de informações pré-contratuais, o considerando n.º 74 dá como exemplos os artigos 6.º e 8.º da Diretiva relativa aos direitos dos consumidores, o artigo 7.º da Diretiva relativa às práticas comerciais desleais[fn:37], os artigos 5.º e 6.º da Diretiva sobre o comércio eletrónico e o artigo 3.º da Diretiva em matéria de indicações dos preços dos produtos oferecidos aos consumidores. Não há, atualmente, uma uniformização destas obrigações de informação no Direito da União Europeia[cite:Cf., considerando que a mesma seria desejável, @hofmann2023, art. 31.º, n.º 1] e, portanto, o fornecedor deve conceber e organizar o interface da sua plataforma em linha de modo a que o comerciante possa cumprir com todas as suas obrigações de informação pré-contratual.

Em matéria da conformidade, parece possível incluir aqui os produtos que, cumpridos os requisitos de conformidade previstos no Direito da União, têm direito a uma declaração UE de confomidade e a ostentar uma marcação UE de conformidade. A plataforma em linha terá, pelo menos, de permitir que os comerciantes forneçam a marcação UE de conformidade dos seus produtos, conforme previsto no n.º 2, al. /c)/[cite:Cf. @hofmann2023, art. 31.º, n.º 13].

Em matéria de informação sobre a segurança dos produtos, releva principalmente o artigo 19.º do Regulamento relativo à segurança geral dos produtos, no qual se estabelece que quando os operadores económicos disponibilizem produtos no mercado em linha ou através de outros meios de venda à distância, a oferta desses produtos deve indicar de forma clara e visível um conjunto mínimo de informações[fn:8].

A interface da plataforma em linha deve permitir aos comerciantes fornecer um conjunto /mínimo/ de informações. Esse elenco parece estar contido no artigo 31.º, n.º 2, atendendo à sua redação[fn:67]. Deve, porém, aditar-se ao elenco as informações sobre o operador económico[fn:79] e deve ter-se em consideração as concretizações efetuadas no artigo 22.º, n.º 9, do Regulamento relativo à segurança geral dos produtos.

** 3. Obrigação prévia de avaliação

Compete ao fornecedor avaliar se o comerciante prestou todas as informações a que se refere o artigo 31.º, n.ºs 1 e 2, antes de o autorizar a utilizar a plataforma em linha para oferecer produtos ou serviços aos consumidores localizados na União Europeia.

O objeto desta avaliação é apenas o de determinar se o comerciante prestou todas as informações, ou seja, se a prestação da informação pelo comerciante foi completa[cite:Contra, @wilman2024, art. 31.º, n.º 13, sustentam que o fornecedor só tem de verificar que a informação foi fornecida, não tendo de verificar se a mesma é fiável e completa] [fn:80]. O fornecedor não está obrigado a avaliar a exatidão das informações[cite:Cf. considerando n.º 74 e @hofmann2023, art. 31.º, n.º 26;@muller-terpitz2023, art. 31.º, n.º 17]. O critério da diligência é também aqui o critério dos "melhores esforços"[fn:81].

Se o fornecedor concluir que as informações fornecidas estão incompletas, deve assegurar-se de que não são oferecidos produtos ou serviços enquanto essas informações não estiverem completas[fn:44].

** 4. Obrigação posterior de verificação

Após autorizar a utilização da plataforma, o fornecedor deve envidar esforços razoáveis para verificar aleatoriamente se estão a ser oferecidos produtos ou serviços na sua plataforma em linha que foram identificados como ilegais. O objeto desta verificação é determinar se algum ou alguns dos produtos ou serviços oferecidos na plataforma foram identificados como ilegais em qualquer base de dados em linha ou interface em linha oficial, de acesso livre e legível por máquina, disponíveis num Estado-Membro ou na União.

Os conceitos de "produto ilegal" e "serviço ilegal" não são definidos no Regulamento dos Serviços Digitais. Traçando um paralelo com o conceito de conteúdos ilegais[fn:68], dir-se-á que produtos ou serviços ilegais são os que não estejam em conformidade com o direito da União ou com o direito de qualquer um dos Estados-Membros que seja conforme com o direito da União, independentemente do objeto ou da natureza precisa desse direito[cite:Cf., neste sentido, @muller-terpitz2023, art. 31.º, n.º 20;@hofmann2023, art. 32.º, n.º 18].

O critério de diligência é o de "esforços razoáveis". Trata-se de um crivo menos exigente do que o de "melhores esforços", consagrado nos artigos 31.º,  n.º 3, 1.º período, e 30.º, n.º 2[cite:Cf., no mesmo sentido, @rocha2024 p. 41]. O Regulamento dos Serviços Digitais não dá orientações sobre o modo de concretização deste critério de diligência.

Trata-se de uma obrigação de verificação aleatória, atendendo a que o fornecedor não tem uma obrigação geral de vigilância[fn:45]. Por esse motivo, o fornecedor não deve verificar /todos/ os produtos ou serviços oferecidos na sua plataforma nem está obrigado a verificar /todos/ os produtos ou serviços oferecidos através de verificações aleatórias /parciais periódicas/[cite:Cf. @muller-terpitz2023, art. 31.º, n.º 22]. A redação não é clara, mas atendendo ao objetivo prosseguido por esta obrigação de verificação, considera-se que a mesma /não/ se cumpre com a realização de /uma/ verificação aleatória, mantendo-se a obrigação enquanto o comerciante ofereça na plataforma em linha produtos ou serviços aos consumidores localizados na União Europeia. Deste modo, a verificação é aleatória quanto aos produtos e serviços sobre que incide, mas deve ser realizada periodicamente[cite:Cf. @hofmann2023, art. 31.º, n.º 30;@muller-terpitz2023 31.º, n.º 22; considerando que tal dependerá do tipo da relação e dos produtos em causa, cf. @rocha2024 p. 41].

A verificação deve ser efetuada através da pesquisa em base de dados em linha ou interface em linha oficial, de acesso livre e legível por máquina, disponíveis num Estado-Membro ou na União. Em matéria de segurança dos produtos, o artigo 22.º, n.º 7, do Regulamento relativo à segurança geral dos produtos estabelece que os fornecedores devem utilizar, pelo menos, o portal do /Safety Gate/.

Se, após a verificação, o fornecedor determinar que um determinado produto ou serviço foi identificado como ilegal, é aplicável o artigo 6.º[cite:Cf. @muller-terpitz2023, art. 31.º, n.º 24].


* V. Obrigações de informação e divulgação em caso de oferta, na plataforma em linha, de produtos ou serviços ilegais

** 1. Considerações gerais

O artigo 32.º impõe aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes duas obrigações - uma de informação aos consumidores outra de divulgação ao público - em caso de oferta, na sua plataforma em linha, de produtos ou serviços ilegais[fn:69]. Há, no entanto, que delimitar o âmbito destas duas obrigações.

Desde logo, o fornecedor só tem a obrigação de informar os consumidores ou divulgar ao público se os produtos ou serviços foram oferecidos e adquiridos por consumidores através da sua plataforma em linha. Se o produto ou serviço ilegal foi oferecido ao consumidor ou adquirido por este por meio diverso da plataforma em linha, quebra-se a conexão decorrente da atual importância destes intermediários no comércio em linha que parece justificar a imposição destas obrigações adicionais[cite:Cf. @muller-terpitz2023, art. 32.º, n.º 8].

As obrigações de informação ou divulgação são aplicáveis quando o produto ou serviço é ilegal, mas não quando (apenas) haja conteúdos ilegais. Assim, e por exemplo, se o produto não for ilegal as obrigações do artigo 32.º não são aplicáveis, mesmo na situação em que as fotos colocadas na plataforma em linha para promover o produto constituam conteúdo ilegal por violarem direitos de autor[cite:Exemplo retirado de @hofmann2023, art. 32.º, n.º 18].

Estas obrigações estão, como as demais que foram sendo analisadas, limitadas em função do âmbito de aplicação espacial do Regulamento dos Serviços Digitais. Por isso, essas obrigações só são aplicáveis se o produto ou serviço ilegal foi oferecido na plataforma em linha por um comerciante a consumidores localizados na União Europeia. Assim, e por exemplo, o artigo 32.º não é aplicável nos casos em que um comerciante ofereça na plataforma em linha produtos que não cumpram a legislação europeia desde que limite a oferta desses produtos a pessoas localizadas fora da União Europeia.

As obrigações de informação e divulgação estão, por fim, limitadas às aquisições de produtos ou serviços ilegais efetuadas durante os seis meses que precedem o momento em que o fornecedor tomou conhecimento da ilegalidade[fn:70]. Assim, e por exemplo, o fornecedor não tem a obrigação de informar os consumidores ou divulgar ao publico que um comerciante ofereceu determinado produto ou serviço ilegal aos consumidores localizados na União Europeia se, nos seis meses anteriores à tomada de conhecimento da ilegalidade pelo fornecedor, nenhum consumidor localizado na União Europeia adquiriu o produto ou serviço ilegal. A data da aquisição é a data em que foi celebrado o contrato entre o comerciante e o consumidor. A data da execução do contrato não é relevante. A data da celebração pode ser facilmente determinada pelo fornecedor, uma vez que o contrato foi celebrado através da sua plataforma em linha[cite:Cf. @hofmann2023, art. 32.º, n.º 29]. A determinação precisa da data em que o fornecedor tomou conhecimento da ilegalidade reveste maior complexidade e variabilidade, atendendo a que o conhecimento pode advir por qualquer meio (cf. /infra/ V.2.).

Com a imposição destas duas obrigações visa-se, primariamente, reforçar a proteção dos consumidores, atribuindo aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes um papel a desempenhar na tarefa de garantir a legalidade dos produtos e serviços oferecidos na União Europeia[cite:Cf., em sentido semelhante, @wilman2024, art. 32.º, n.º 1;@hofmann2023, art. 32.º, n.ºs 1 e 3;@muller-terpitz2023, art. 32.º, n.º 2;@mast2024, art. 32.º, n.º 2]. Protege-se também os comerciantes concorrentes e os titulares de direitos de propriedade intelectual[cite:Cf. @hofmann2023, art. 32.º, n.º 2;@mast2024, art. 32.º, n.º 3] e pode, inclusive, produzir-se um efeito disuasor na oferta de produtos e serviços ilegais atendendo aos (potencialmente muito elevados) danos reputacionais e patrimoniais que podem advir da informação aos consumidores ou divulgação ao público de que determinado comerciante ofereceu produtos ou serviços ilegais.

** 2. Obrigação de informar os consumidores que adquiriram o produto ou serviço ilegal

São dois os pressuspostos da obrigação de informar os consumidores: /(i)/ o fornecedor tem de tomar conhecimento de que foi oferecido um produto ou serviço ilegal através da sua plataforma em linha; e /(ii)/ tem de dispor dos dados de contacto dos consumidores localizados na União Europeia que adquiriram esse produto ou serviço ilegal.

Da redação do preceito, conjugada com a ausência de uma obrigação geral de vigilância[fn:71], resulta que não é suficiente o fornecedor ter conhecimento, em sentido geral, de que o seu serviço é utilizado para oferecer produtos ou serviços ilegais. O fornecedor tem de tomar conhecimento concreto de que /determinado/ produto ou serviço ilegal é oferecido na sua plataforma em linha[fn:47]. O conhecimento abrange o /concreto/ produto ou serviço /e/ a sua natureza ilegal[cite:Cf. @hofmann2023, art. 32.º, n.º 12].

O meio utilizado para obter conhecimento é irrelevante. O conhecimento pode advir por qualquer meio, nomeadamente através de investigações realizadas por iniciativa própria, verificações efetuadas ao abrigo do artigo 31.º, n.º 3, ou notificações remetidas ao fornecedor[cite:Cf., no mesmo sentido, @mast2024, art. 32.º, n.º 8]. Quanto a estas últimas recorda-se a jurisprudência do TJ, proferida no contexto do artigo 14.º da Diretiva sobre o comércio eletrónico, de que "uma notificação não pode automaticamente retirar o direito à isenção de responsabilidade prevista no artigo 14.º da Directiva 2000/31, dado que as notificações de actividades ou informações alegadamente ilegais se podem revelar insuficientemente precisas e demonstradas"[fn:48].

No contexto do artigo 32.º, em que o cumprimento da obrigação de informação pode acarretar danos reputacionais muito elevados para o comerciante, considera-se que o fornecedor deve ser cuidadoso ao estabelecer o conhecimento da ilegalidade do produto ou serviço. Por exemplo, nos casos em que é alertado para a ilegalidade de determinado produto ou serviço por notificações de terceiros, o fornecedor deverá previamente dar uma oportunidade ao comerciante para se pronunciar[cite:Cf. @hofmann2023, art. 32.º, n.ºs 13 e ss.].

O fornecedor só tem a obrigação de informar o consumidor se dispuser dos seus dados de contacto, mas não se encontra obrigado a ter e a tratar esses dados de contacto para este propósito[cite:@wilman2024 32.º, n.º 3, consideram que o estabelecimento de tal obrigação violaria o artigo 6.º, n.º 1 do RGPD].

Preenchidos os pressupostos, o fornecedor tem a obrigação de informar o consumidor: /(i)/ de que o produto ou serviço é ilegal; /(ii)/ da identidade do comerciante; e /(iii)/ de quaisquer meios de reparação aplicáveis[fn:72].

Aparentemente, o fornecedor teria apenas o dever de informar que o produto ou serviço adquirido é ilegal[cite:Cf. @muller-terpitz2023, art. 32.º, n.º 11; /Contra/ @mast2024, art. 32.º, n.º 16]. Alguns autores sustentam que o dever de indicar o fundamento da ilegalidade decorre, implicitamente, da obrigação de informar o consumidor de quaiquer meios de reparação aplicáveis[cite:Cf. @hofmann2023, art. 32.º, n.º 23].

O conceito de identidade não é definido no Regulamento dos Serviços Digitais. Alguns autores sustentam que o conceito de identidade, em regra, não abrangerá o endereço[cite:Cf. @hofmann2023, art. 32.º, n.º 25]. Outros reconduzem este conceito à informação que o fornecedor deve ter obtido do comerciante[cite:Cf. artigo 30.º, n.º 1, al. /a)/, e @muller-terpitz2023, art. 32.º, n.º 11;@mast2024, art. 32.º, n.º 16]. Este último entendimento parece ser preferível, atendendo ao objetivo de reforçar a proteção do consumidor e à relevância do endereço postal para o exercício judicial dos direitos do consumidor.

A análise das várias versões linguísticas aponta no sentido de que não é suficiente uma comunicação, de caráter geral, ao consumidor sobre os seus direitos. Parece ser necessário uma adequação da informação a prestar às circunstâncias do caso concreto, considerando que o consumidor deve ser informado dos meios de reparação /pertinentes/[fn:73]. O Regulamento dos Serviços Digitais não dá indicações sobre esta matéria. Parece dever procurar-se um equilíbrio entre o encargo imposto aos fornecedores, que não deverá ser excessivo, e o objetivo de reforçar, através da prestação desta informação, a proteção dos consumidores. Assim, não devem ser indicados todos os direitos do consumidor, pois o excesso de informação pode dificultar o exercício dos seus direitos. Por outro lado, o fornecedor não deverá ser onerado com a obrigação de efetuar uma delimitação precisa dos meios de reparação aplicáveis. Devem ser indicados os meios de reparação que, em princípio, podem ser aplicáveis ao caso concreto[cite:Cf. @hofmann2023, art. 32.º, n.º 26;@muller-terpitz2023, art. 32.º, n.º 12].

Não é definido como deve o fornecedor comunicar a informação aos consumidores. Regra geral, admite-se que a solução mais comum será o envio da informação através de mensagem para o endereço de correio eletrónico do consumidor. A informação pode também ser prestada mediante envio de carta para o endereço postal do consumidor. A prestação da informação ao consumidor mediante contacto telefónico não parece adequada, desde logo pela quantidade de informação a prestar, pelos maiores encargos que acarreta para o fornecedor[cite:Cf. @muller-terpitz2023, art. 32.º, n.º 13] e por não consubstanciar um registo duradouro que permita consultas repetidas pelo consumidor. Parece, no entanto, possível - embora não tão comum como o envio de mensagens por correio eletrónico - o envio da informação através de aplicações de troca de mensagens que utilizem o contacto telefónico para identificar os seus utilizadores[fn:74].

Em contraponto, a prestação da informação através da própria plataforma em linha - mesmo quando esta tenha um sistema interno de troca de mensagens - não parece poder incluir-se no conceito de dados de contacto, pois normalmente pressupõe que o consumidor tem de aceder à plataforma em linha para verificar as mensagens[cite:Cf., em sentido semelhante, @muller-terpitz2023, art. 32.º, n.º 13].

** 3. Obrigação de divulgação

A obrigação de divulgação ao público, prevista no artigo 32.º, n.º 2, substitui a obrigação de informação aos consumidores, nos casos em que o fornecedor não disponha dos dados de contacto de nenhum dos consumidores adquirentes. Pode, no entanto, questionar-se se o mesmo sucede nos casos em que o fornecedor dispõe dos dados de contacto de alguns, mas não de todos os consumidores adquirentes. Ou se, neste caso, o fornecedor está obrigado a informar diretamente os consumidores adquirentes cujos meios de contacto dispõe e a cumprir a obrigação de divulgação, pois não tem a possibilidade de informar diretamente os restantes consumidores adquirentes. Atendendo ao objetivo de proteção dos consumidores, e ao facto de a obrigação de divulgação não garantir o conhecimento por parte dos consumidores adquirentes (uma vez que estes têm de se dirigir à plataforma em linha para consultarem a informação), entende-se que, nos casos em que o fornecedor só disponha dos dados de contacto de parte dos consumidores adquirentes, ele deve cumprir a obrigação de informação quanto a estes e também a obrigação de divulgação ao público.

A obrigação de divulgação ao público abrange as informações sobre o produto ou serviço ilegal, a identidade do comerciante e quaisquer meios de reparação aplicáveis. A expressão "informações sobre o produto ou serviço ilegal" parece ser mais abrangente do que a prevista no artigo 32.º, n.º 1, al. /a)/. Tal pode compreender-se porque, neste caso, o fornecedor não pode contactar diretamente todos os consumidores que adquiriram o produto ou serviço ilegal e, por isso, deve divulgar informações que permitam aos consumidores identificar inequivocamente se adquiriram ou não aquele produto ou serviço ilegal. Assim, inclui-se, por exemplo, a designação, modelo, n.º de série, descrição e imagens do produto ilegal[cite:Cf. @muller-terpitz2023, art. 32.º, n.º 16]. As informações relativas à identidade do comerciante e aos meios de reparação correspondem às previstas no artigo 32.º, n.º 1, als. /b)/ e /c)/ (cf. /supra/ V.2.).

Estas informações devem ser disponibilizadas ao público, de modo facilmente acessível, na interface em linha da plataforma em linha do fornecedor. O requisito de disponibilização ao público é preenchido desde que a informação seja colocada em local da plataforma em linha que possa ser acedido por qualquer internauta, mesmo que não tenha conta na plataforma em linha (ou não tenha acedido a esta)[cite:Cf. @hofmann2023, art. 32.º, n.º 32;@muller-terpitz2023, art. 32.º, n.º 18]. As informações são facilmente acessíveis se o público consegue aceder à informação sem necessitar de pesquisar muito por ela[cite:Cf. @muller-terpitz2023, art. 32.º, n.º 19], não devendo a interface em linha constituir um entrave ao acesso à informação[cite:Cf., no contexto do artigo 14.º, @knapp2024, p. 113]. Um modo de o alcançar será, por exemplo, criar uma secção específica na interface em linha da plataforma em linha, acessível desde logo na página de entrada da plataforma, para a divulgação destas informações[cite:Cf. @hofmann2023, art. 32.º, n.º 32].

* VI. Considerações finais
Terminado este breve excurso pelas disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes no Regulamento dos Serviços Digitais, há que efetuar (também breves) considerações finais.

É, pensa-se, de louvar a inclusão desta secção no Regulamento dos Serviços Digitais e a consagração de deveres adicionais aos fornecedores de plataformas em linha que permitem a celebração de contratos entre comerciantes e consumidores, com o primário intuito de proteção destes últimos.

Compreende-se a isenção subjetiva concedida aos fornecedores que sejam micro ou pequenas empresas, na aceção da Recomendação 2003/361/CE, atentos os objetivos prosseguidos. A isenção subjetiva cede quando a micro ou pequena empresa seja a fornecedora de uma plataforma em linha que tenha sido designada como de muito grande dimensão, considerando o maior alcance e impacto das plataformas em linha de muito grande dimensão. Embora improvável, caso tal situação se verifique, sustenta-se que estas disposições devem ser aplicáveis quatro meses após a notificação ao fornecedor da designação da plataforma como plataforma em linha de muito grande dimensão, aplicando analogicamente o prazo de quatro meses previsto no artigo 33.º, n.º 6, 2.º parágrafo.

A obrigação de rastreabilidade dos comerciantes, assente no princípio /Know Your Business Customer/, é um passo muito relevante na proteção dos consumidores e também de outras partes interessadas. A aplicação prática desta obrigação será interessante de acompanhar, atendendo ao critério de diligência adotado (melhores esforços) para a obrigação de avaliação prévia da fiabilidade e completude das informações prestadas pelos comerciantes.

A obrigação de conformidade desde a conceção traduz a adaptação do /privacy by design/ do Regulamento Geral de Proteção de Dados: visa-se, com esta obrigação, reforçar a proteção dos consumidores através da conceção técnica das plataformas em linha. Considera-se que poderiam estar melhor delineados os contornos da obrigação posterior de verificação aleatória se estão ou não a ser oferecidos produtos ou serviços identificados como ilegais na sua plataforma em linha. Entende-se que esta obrigação /não/ se cumpre com a realização de /uma/ verificação aleatória, mantendo-se a obrigação enquanto o comerciante ofereça na plataforma em linha produtos ou serviços aos consumidores localizados na União Europeia. Deste modo, a verificação é aleatória quanto aos produtos e serviços sobre que incide, mas deve ser realizada periodicamente.

As obrigações de informação dos consumidores adquirentes e ou de divulgação ao público em caso de oferta, na plataforma em linha, de produtos ou serviços ilegais, conferem aos fornecedores destas plataformas em linha um papel a desempenhar na tarefa de garantir a legalidade dos produtos e serviços oferecidos na União Europeia. Estas obrigações estão sujeitas a diversas limitações e destaca-se a temporal: as obrigações de informação e divulgação só existem se os produtos ou serviços ilegais foram adquiridos, na plataforma em linha do fornecedor e por consumidores localizados na União Europeia, nos seis mess que que precedem o momento em que o fornecedor tomou conhecimento da ilegalidade. É debatível se este prazo de seis meses traduz uma adequada ponderação dos valores em presença. A articulação destas duas obrigações também é digna de nota. A obrigação de divulgação ao público substitui a obrigação de informação aos consumidores, nos casos em que o fornecedor não disponha dos dados de contacto de nenhum dos consumidores adquirentes. Quando o fornecedor disponha dos dados de contacto de alguns mas não de todos os consumidores adquirentes, entende-se - considerando o objetivo de poteção dos consumidores - que ele deve cumprir a obrigação de informação quanto aos consumidores adquirentes cujos dados de contacto possui e também a obrigação de divulgação ao público.

Apesar destes apontamentos, a avaliação, no cômputo geral, é positiva, considerando-se que as disposições constituem um inegável reforço da tutela dos consumidores (localizados na União Europeia) no espaço digital.


* Footnotes
[fn:9] /V.g./, criando, adicionalmente, uma secção dedicada na sua plataforma em linha onde seja possível pesquisar as informações relativas a todos os comerciantes que operam na sua plataforma.

[fn:8] A saber: /(i)/ nome, denominação comercial registada ou marca registada do fabricante e endereço postal e eletrónico para contacto; /(ii)/ nome, endereço postal e eletrónico do operador económico estabelecido na União Europeia, quando o fabricante não esteja estabelecido na União Europeia; /(iii)/ informações que permitam identificar o produto, incluindo uma imagem do mesmo, o seu tipo e qualquer outro identificador do produto; e /(iv)/ alertas ou informações de segurança que devem ser apostas no produto ou na embalagem ou incluídas num documento que acompanhe o produto, de acordo com o presente regulamento ou com a legislação de harmonização da União aplicável, numa língua que possa ser facilmente compreendida pelos consumidores, conforme determinado pelo Estado-Membro em que o produto é disponibilizado no mercado.

[fn:81] Cf. /supra/ III.3.

[fn:80] Contraste-se com o artigo 30.º, n.º 2 (cf. /supra/ III.3.), que exige que o fornecedor avalie se as informações são fiáveis e completas.

[fn:79] Cf. artigo 31.º, n.º 1, 2.º parágrafo.

[fn:3] O artigo 30.º, n.º 1, parte do pressuposto de que o comerciante ainda não utiliza a plataforma em linha do fornecedor. Foi prevista uma disposição transitória no artigo 30.º, n.º 2, 2.º parágrafo, establecendo que o fornecedor deveria solicitar aos comerciantes que já utilizavam a plataforma em linha na data em que se tornaram aplicáveis as normas do Regulamento dos Serviços Digitais a prestação das informações elencadas no n.º 1. Se estes não fornecessem as informações até 17 de fevereiro de 2025, os fornecedores deveriam suspender o fornecimento dos seus serviços a tais comerciantes até que lhes fossem fornecidas todas as informações.

[fn:78] Cf. artigo 3.º, al. /r)/.

[fn:77] Cf. artigo 33.º e ss.

[fn:76] Cf. artigo 29.º, n.º 1, 2.º parágrafo. Uma empresa perde o estatuto de micro ou pequena empresa se, numa base anual, superar o limiar de efetivos e ou os limiares financeiros /e/ se tal se repetir durante dois exercícios consecutivos (artigo 4.º, n.º 2, do Anexo da Recomendação 2003/361/CE).

[fn:74] /V.g./, /Whatsapp/.

[fn:73] Cf. as versões inglesa, francesa, italiana, espanhola e alemã do Regulamento dos Serviços Digitais que indicam, respetivamente, que o consumidor deve ser informado de /"any relevant means of redress/, /"tout moyen de recours pertinent"/, /"di qualsiasi mezzo di ricorso pertinente"/, /"de cualquier vía de recurso pertinente"/ e /"die einschlägigen Rechtsbehelfe"/.

[fn:72] Cf., respetivamente, artigo 32.º, n.º 1, als. /a)/ a /c)/.

[fn:71] Cf. artigo 8.º.

[fn:70] Cf. artigo 32.º, n.º 1, 2.º parágrafo.

[fn:69] Sobre o conceito de produto ou serviço ilegal, cf. /supra/ IV.4..

[fn:68] Definido no artigo 3.º, al. /h)/.

[fn:67] Na qual se estabelece: "a sua interface em linha é concebida e organizada de forma a permitir que os comerciantes forneçam, /pelo menos/, os seguintes elementos" (itálicos aditados).

[fn:66] Este conceito encontra-se definido no artigo 3.º, al. /m)/, e, em linguagem não técnica, abrange os programas informáticos, entendidos de forma ampla, que permitem ao comerciante aceder e interagir com a plataforma em linha.

[fn:65] Cf. artigo 2.º e referências bibliográficas indicadas na nota de rodapé n.º *fazer referência cruzada*.

[fn:64] Cf. artigo 31.º, n.º 3, segundo período.

[fn:63] Cf. artigo 31.º, n.º 3, primeiro período.

[fn:62] Cf. artigo 31.º, n.ºs 1 e 2.

[fn:61] Os conceitos de "interface em linha" e "plataforma em linha" estão definidos no artigo 3.º, als. /i)/ e /m)/.

[fn:60] Cf., respetivamente, artigo 30.º, n.º 1, als. /b)/ e /c)/.

[fn:59] Cf. artigo 30.º, n.º 3.

[fn:58] Directiva (UE) 2019/790 do Parlamento Europeu e do Conselho, de 17 de abril de 2019, relativa aos direitos de autor e direitos conexos no mercado único digital e que altera as Directivas n.º 96/9/CE e n.º 2001/29/CE, publicada no JO L 130 de 17 de maio de 2019.

[fn:57] Cf. artigo 30.º, n.º 2, 1.º parágrafo, /in fine/.

[fn:56] Cf. artigo 30.º, n.º 1, al. /e)/.

[fn:55] Cf. aritgo 30.º, n.º 1, al. /d))/.

[fn:54] Cf. artigo 30.º, n.º 1, al. /c)/.

[fn:53] Cf. artigo 30.º, n.º 1, al. /b)/.

[fn:52] Cf. artigo 30.º, n.º 1, al. /a)/.

[fn:1] Assinala-se que apesar de o conceito de "comerciante" se encontrar definido no artigo 3.º, o considerando n.º 72 indica que "(...) qualquer comerciante, independentemente de ser uma pessoa singular ou coletiva, identificado como tal com base no artigo 6.º-A, n.º 1, alínea /b)/, da Diretiva 2011/83/UE e no artigo 7.º, n.º 4, alínea /f)/, da Diretiva 2005/29/CE, deverá ser rastreável quando oferece um produto ou serviço através de uma plataforma em linha."

[fn:51] Tratado sobre o Funcionamento da União Europeia (versão consolidada), publicado no JO C 202 de 7 de junho de 2016.

[fn:50]Cf. artigos 153.º, n.º 2, al. /b)/, e 173.º, n.º 1, 2.º travessão, do TFUE.

[fn:16]Cf. artigos 12.º e 169.º do TFUE.


[fn:5a] Directiva 2000/31/CE do Parlamento Europeu e do Conselho de 8 de Junho de 2000 relativa a certos aspectos legais dos serviços da sociedade de informação, em especial do comércio electrónico, no mercado interno («Directiva sobre o comércio electrónico»), publicada no JO L 178, de 17 de julho de 2000.

[fn:4a] Directiva 2000/31/CE do Parlamento Europeu e do Conselho de 8 de Junho de 2000 relativa a certos aspectos legais dos serviços da sociedade de informação, em especial do comércio electrónico, no mercado interno («Directiva sobre o comércio electrónico»), publicada no JO L 178, de 17 de julho de 2000.

[fn:1a] Regulamento (UE) 2022/2065 do Parlamento Europeu e do Conselho de 19 de outubro de 2022 relativo a um mercado único para os serviços digitais e que altera a Diretiva 2000/31/CE (Regulamento dos Serviços Digitais), publicado no Jornal Oficial da União Europeia (JO) L 277 de 27 de outubro de 2022. Doravante os artigos e considerandos citados sem indicação de fonte pertencem a este Regulamento, salvo se o contrário resultar do contexto.

[fn:48] Cf. Acórdão do TJ de 12 de julho de 2011, /L'Oréal e o./, proc. C-324/09, EU:C:2011:474, n.º 122.

[fn:47] Cf., no contexto do artigo 6.º, o considerando n.º 22 e, no contexto do artigo 14.º da Diretiva sobre o comércio eletrónico, o Acórdão do TJ de 22 de junho de 2021, /YouTube e Cyando/, processos apensos C-682/18 e C-683/18, EU:C:2021:503, n.ºs 113 e 114.

[fn:46] Cf. Relatório sobre a proposta de Regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE, de 20.12.2021, (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), alteração 246, p. 514.

[fn:45] Cf. artigo 8.º e considerando n.º 74.

[fn:44] Cf. considerando n.º 74.

[fn:41] Cf., respetivamente, artigos 19.º e 20.º do Regulamento relativo aos dispositivos médicos.

[fn:40] Regulamento (UE) 2017/745 do Parlamento Europeu e do Conselho, de 5 de abril de 2017, relativo aos dispositivos médicos, que altera a Diretiva 2001/83/CE, o Regulamento (CE) n.° 178/2002 e o Regulamento (CE) n.° 1223/2009 e que revoga as Diretivas 90/385/CEE e 93/42/CEE do Conselho, publicado no JO L 117 de 5.5.2017.

[fn:39] Cf. exemplos enunciados no considerando n.º 74.

[fn:38] Diretiva 98/6/CE do Parlamento Europeu e do Conselho, de 16 de fevereiro de 1998, relativa à defesa dos consumidores em matéria de indicações dos preços dos produtos oferecidos aos consumidores, publicada no JO L 80 de 18.3.1998.

[fn:37] Diretiva 2005/29/CE do Parlamento Europeu e do Conselho, de 11 de maio de 2005, relativa às práticas comerciais desleais das empresas face aos consumidores no mercado interno e que altera a Diretiva 84/450/CEE do Conselho, as Diretivas 97/7/CE, 98/27/CE e 2002/65/CE e o Regulamento (CE) n.º 2006/2004, publicada no JO L 149 de 11.6.2005.

[fn:36] Cf. Relatório sobre a proposta de Regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE, de 20.12.2021, (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), alteração 245, p. 513.

[fn:35] Cf. Considerando n.º 72.

[fn:33] Cf. Considerando n.º 72.

[fn:32] Regulamento (UE) 2019/1150 do Parlamento Europeu e do Conselho, de 20 de junho de 2019, relativo à promoção da equidade e da transparência para os utilizadores profissionais de serviços de intermediação em linha, publicado no JO L 186 de 11.7.2019.

[fn:31] Comunicação da Comissão ao Parlamento Europeu e ao Conselho : Orientações sobre o artigo 17.º da Diretiva 2019/790 relativa aos direitos de autor no mercado único digital, COM(2021) 288 final, 4.6.2021, pp. 9 e ss.

[fn:30] Cf. considerando n.º 73.

[fn:29] Cf. considerando n.º 73.

[fn:28] Cf. considerando n.º 73.

[fn:27] Regulamento (UE) 2015/751 do Parlamento Europeu e do Conselho, de 29 de abril de 2015, relativo às taxas de intercâmbio aplicáveis a operações de pagamento baseadas em cartões, publicado no JO L 123 de 19.5.2015.

[fn:25] Regulamento (UE) n.º 910/2014 do Parlamento Europeu e do Conselho, de 23 de julho de 2014, relativo à identificação eletrónica e aos serviços de confiança para as transações eletrónicas no mercado interno e que revoga a Diretiva 1999/93/CE, publicado no JO L 257 de 28.8.2014.

[fn:24] Cf. Acórdão de 10 de julho de 2019, /Amazon EU/, C-649/17, EU:C:2019:576, considerando n.º 51.

[fn:23] Regulamento (UE) n.º 1215/2012 do Parlamento Europeu e do Conselho, de 12 de dezembro de 2012, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial (reformulação), publicado no JO L 351 de 20.12.2012.

[fn:22] Directiva 2011/83/UE do Parlamento Europeu e do Conselho, de 25 de Outubro de 2011, relativa aos direitos dos consumidores, que altera a Directiva 93/13/CEE do Conselho e a Directiva 1999/44/CE do Parlamento Europeu e do Conselho e que revoga a Directiva 85/577/CEE do Conselho e a Directiva 97/7/CE do Parlamento Europeu e do Conselho, publicada no JO L 304 de 22.11.2011.

[fn:21] Directiva 2006/123/CE do Parlamento Europeu e do Conselho, de 12 de Dezembro de 2006, relativa aos serviços no mercado interno, publicada no JO L 376 de 27.12.2006.

[fn:20] Diretiva (UE) 2019/771 do Parlamento Europeu e do Conselho, de 20 de maio de 2019, relativa a certos aspetos dos contratos de compra e venda de bens que altera o Regulamento (UE) 2017/2394 e a Diretiva 2009/22/CE e que revoga a Diretiva 1999/44/CE, publicada no JO L 136 de 22.5.2019.

[fn:19] Introduzido pela Diretiva (UE) 2019/2161 do Parlamento Europeu e do Conselho de 27 de novembro de 2019 que altera a Diretiva 93/13/CEE do Conselho e as Diretivas 98/6/CE, 2005/29/CE e 2011/83/UE do Parlamento Europeu e do Conselho a fim de assegurar uma melhor aplicação e a modernização das regras da União em matéria de defesa dos consumidores, publicada no JO L 328 de 18 de dezembro de 2019.

[fn:18] Cf. Considerando n.º 72.

[fn:17] Cf. Considerando n.º 72.

[fn:14] Cf. Acórdãos de 27 de fevereiro de 2014, /HaTeFo/, C-110/13, EU:C:2014:114, considerando n.º 32, de 24 de setembro de 2020, /NMI Technologietransfer/, C-516/19, EU:C:2020:754, considerando n.º 65, e de 10 de março de 2021, /Ertico - ITS Europe contra Comissão Europeia/, C-572/19 P, EU:C:2021:188, considerando n.º 89.

[fn:7] Recomendação da Comissão, de 6 de Maio de 2003, relativa à definição de micro, pequenas e médias empresas, notificada com o número C(2003) 1422, publicada no JO L 124, de 20 de maio de 2003.

[fn:6] Cf. artigo 22.º do Regulamento (UE) 2023/988 do Parlamento Europeu e do Conselho de 10 de maio de 2023 relativo à segurança geral dos produtos, que altera o Regulamento (UE) n.o 1025/2012 do Parlamento Europeu e do Conselho e a Diretiva (UE) 2020/1828 do Parlamento Europeu e do Conselho e que revoga a Diretiva 2001/95/CE do Parlamento Europeu e do Conselho e a Diretiva 87/357/CEE do Conselho, publicado no JO L 135, de 23 de maio de 2023.

[fn:5] Cf., neste sentido, Parecer do Comité Económico e Social Europeu sobre a «Proposta de regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE», publicado no JO C 286, de 16 de julho de 2021, ponto 3.7. Assinala-se que as micro e pequenas empresas beneficiam de outras isenções subjetivas nos artigos 15.º, n.º 2 e 19.º, prevendo-se no artigo 91.º, n.º 2, al. /d)/, a revisão destas isenções até 17 de novembro de 2027 e a partir daí quinquenalmente.

[fn:4] Cf. considerando n.º 57.

[fn:2] Cf. o /Provisional Agreement resulting from Interinstitutional Negotiations/, de 15 de junho de 2022, doc. PE734.11, disponível em https://oeil.secure.europarl.europa.eu/oeil/en/procedure-file?reference=2020/0361(COD) e consultado pela última vez em 20 de fevereiro de 2025.
